[tool.commitizen]
version = "1.2.7"
name = "cz_conventional_commits"
bump_message = "bump: version $current_version → $new_version [skip ci]"
tag_format = "$version"
version_scheme = "semver"
update_changelog_on_bump = true
